-- ****** Object: RelationalTable SCOTT.EMP Script Date: 4/30/2020 6:38:46 PM ******
  CREATE TABLE "SCOTT"."EMP" 
   (	"EMPNO" NUMBER(4,0),
	"ENAME" VARCHAR2(10),
	"JOB" VARCHAR2(9),
	"MGR" NUMBER(4,0),
	"HIREDATE" DATE,
	"SAL" NUMBER(7,2),
	"COMM" NUMBER(7,2),
	"DEPTNO" NUMBER(2,0),
	CONSTRAINT "PK_EMP" PRIMARY KEY ("EMPNO") ENABLE,
	CONSTRAINT "FK_DEPTNO" FOREIGN KEY ("DEPTNO")
	 REFERENCES "SCOTT"."DEPT" ("DEPTNO") ENABLE
   );